# coding: utf-8


try:
    # генерация исключения
    raise Exception('Произошло исключение!!!')

except:
    print('Обработали')





